<?php

/**
 * PluginNice
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    opNicePlugin
 * @subpackage lib
 * @author     Hiromi Hishida<info@77-web.com>
 * @version    0.1
 */
abstract class PluginNice extends BaseNice
{
  protected $foreignObject = null;

  public function getForeignObject()
  {
    if($this->foreignObject) return $this->foreignObject;
    
    $obj = Doctrine::getTable($this->getForeignTable())->find($this->getForeignId());
    if($obj)
    {
      $this->foreignObject = $obj;
      return $this->foreignObject;
    }
    return null;
  }
  
  public function getForeignTitle()
  {
    $key = "name";
    if($this->getForeignTable()=="Diary")
    {
      $key = "title";
    }
    return $this->getForeignObject()?$this->getForeignObject()->get($key):'';
  }
  
  public function getForeignUrl()
  {
    $url = "";
    switch($this->getForeignTable())
    {
      case "Diary":
        $url = "diary/show?id=".$this->getForeignId();
        break;
      case "CommunityTopic":
        $url = "communityTopic/show?id=".$this->getForeignId();
        break;
      case "CommunityEvent":
        $url = "communityEvent/show?id=".$this->getForeignId();
        break;
    }
    return $url;
  }
  
  public function getForeignDate()
  {
    return $this->getForeignObject()?$this->getForeignObject()->getCreatedAt():'';
  }
  
  public function isDeletable($memberId)
  {
    return $this->getMemberId() == $memberId;
  }
}