<?php

/**
 * PluginNiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginNiceTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginNiceTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PluginNice');
    }
}