<?php

/**
 * PluginNiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginNiceTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginNiceTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginNice');
  }
  
  public function getNicedList($table, $id, $limit=0)
  {
    $q = $this->createQuery('n')->where('foreign_table = ? AND foreign_id = ?', array($table, $id))->orderBy('created_at');
    
    if($limit>0)
    {
      $q->limit($limit);
    }
    
    return $q->execute();
  }
}