<?php

/**
 * PluginNiceTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginNiceTable extends Doctrine_Table
{
  /**
   * Returns an instance of this class.
   *
   * @return object PluginNiceTable
   */
  public static function getInstance()
  {
    return Doctrine_Core::getTable('PluginNice');
  }
  
  public function getNicedList($table, $id, $limit=0)
  {
    $q = $this->createQuery('n')->where('foreign_table = ? AND foreign_id = ?', array($table, $id))->orderBy('created_at');
    
    if($limit>0)
    {
      $q->limit($limit);
    }
    
    return $q->execute();
  }
  
  public function getNicedCount($table, $id)
  {
    return $this->createQuery('n')->where('foreign_table = ? AND foreign_id = ?', array($table, $id))->count();
  }
  
  public function isAlreadyNiced($memberId, $table, $id)
  {
    return $this->createQuery('n')->where('member_id = ? AND foreign_table = ? AND foreign_id = ?', array($memberId, $table, $id))->count()>0;
  }
  
  public function getMemberPager($foreignTable, $foreignId, $size, $page = 1)
  {
    if($page < 1) $page = 1;
    $q = $this->createQuery('n')->addWhere('n.foreign_table = ? AND n.foreign_id = ?', array($foreignTable, $foreignId))->orderBy('n.created_at DESC');
    
    $pager = new sfDoctrinePager('Nice', $size);
    $pager->setQuery($q);
    $pager->setPage($page);
    $pager->init();
    
    return $pager;
  }
  
  public function getContentPager($memberId, $size, $page = 1)
  {
    if($page < 1) $page = 1;
    $q = $this->createQuery('n')->addWhere('n.member_id = ?', $memberId)->orderBy('n.created_at DESC');
    
    $pager = new sfDoctrinePager('Nice', $size);
    $pager->setQuery($q);
    $pager->setPage($page);
    $pager->init();
    
    return $pager;
  }
}